### ISSUE TITLE
Split topBar component out of Main component

### ISSUE THREAD

**Issue by zt1983811** [golang-cms/cms-admin#2]
Split topBar component out of Main component

**Comment by zt1983811** [comment]
Task has been done please review https://github.com/golang-cms/cms-admin/pull/3 @zt1983811

**Comment by hkcj** [comment]
I'm not sure how i should read this.
I see the projects tab, is there soemthing assigned to me?

**Comment by zt1983811** [comment]
> I'm not sure how i should read this.
> I see the projects tab, is there soemthing assigned to me?

Yes HK, this issue is assign to you
I believe you can extract TopBar component out of `Main.tsx` component. Let me know if the requirement is clear or not.

**Comment by hkcj** [comment]
Is the topBar the AppBar?
There is a comment stating that we should run npm start to 'begin development', is that something we ignore?

**Comment by hkcj** [comment]
I have a feel of how the components are separated. I'm sorry, i'm a bit confused.
I can't seem to render the page on browser. it makes more confusion for me of what I'm working on.
I still not completely sure if I should create a new topbar or locate and extract it.
It looks like the whole thing is the leftMenu if I'm not mistaken.

**Comment by zt1983811** [comment]
@hkcj  I have done for leftMenu, the component that need to be extracted is `TopBar`, for now it's in `src/admin/moudles/Main.tsx` line 127. I believe you could create a new file call `TopBar.tsx` under `src/admin/moudles/common/TopBar.tsx`  and move the component there. 

If you have problem running `npm start` then let's create a meeting tomorrow to check

**Comment by hkcj** [comment]
I see the topBar now, in gitHub. It's not in my cloned version, somehow.
Yes, I have errors when I do npm start. I'm in dire need of help, lol.
Please let me know when tomorrow.
